### ISSUE TITLE
Wrong type for pin 38

### ISSUE THREAD

**Issue by SukkoPera** [ncarandini/KiCad-RP-Pico#6]
Pin 38 (GND) has _Bidirectional_ type, while I think it should be classified as _Power Input_.

PS: Thanks for your work! :)

**Comment by ncarandini** [comment]
Hi, can you further explain? To me GND is GND :-)

**Comment by SukkoPera** [comment]
Exactly, but it's [currently set as _Bidirectional_](https://github.com/ncarandini/KiCad-RP-Pico/blob/main/RP-Pico%20Libraries/MCU_RaspberryPi_and_Boards.lib#L45) in your component.

**Comment by ncarandini** [comment]
I'll fix it ASAP.

**Comment by voidloop** [comment]
Is not pin 36 (3V3) also wrong? I think it should be as power output.

Thanks for your work!

**Comment by SukkoPera** [comment]
@voidloop: Yes, you are right, that should be fixed, too.

**Comment by Poofjunior** [comment]
![pico_bidirectional](https://user-images.githubusercontent.com/706699/171282705-633bcb3d-fbbe-4973-88f1-008b1d457f3e.png)

Whoop--looks like this is still an issue. Happy to do a PR if that's easier for ya ;)

**Comment by Poofjunior** [comment]
PR https://github.com/ncarandini/KiCad-RP-Pico/pull/8 made. Hopefully, this saves ya some work.
